<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251211110236 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajout des entités Adresse, BatimentRnb et Point pour enregistrement des données réconciliées avec leurs bâtiments RNB';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE adresse (code_bat_ter INT NOT NULL, region VARCHAR(255) NOT NULL, departement INT NOT NULL, die_adresse VARCHAR(1020) DEFAULT NULL, meilleure_adresse_rnb VARCHAR(1020) DEFAULT NULL, score_levenshtein DOUBLE PRECISION NOT NULL, fiabilite_adresse VARCHAR(255) NOT NULL, cas_adresse VARCHAR(255) NOT NULL, definition_cas VARCHAR(255) NOT NULL, fiabilite_rnb_die_vs_cerema VARCHAR(255) NOT NULL, fiabilite VARCHAR(255) NOT NULL, source VARCHAR(255) NOT NULL, rnb_ids JSON NOT NULL, geometry VARCHAR(1020) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updatedat TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C35F0816100F0C54 ON adresse (code_bat_ter)');
        $this->addSql('CREATE TABLE batiment_rnb (rnd_id INT NOT NULL, status VARCHAR(255) NOT NULL, active BOOLEAN NOT NULL, adresses_cles_interop JSON NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, point_id INT DEFAULT NULL, adresse_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_11917487FC6EB833 ON batiment_rnb (rnd_id)');
        $this->addSql('CREATE INDEX IDX_11917487C028CEA2 ON batiment_rnb (point_id)');
        $this->addSql('CREATE INDEX IDX_119174874DE7DC5C ON batiment_rnb (adresse_id)');
        $this->addSql('CREATE TABLE point (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, longitude DOUBLE PRECISION NOT NULL, latitude DOUBLE PRECISION NOT NULL, polygone_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B7A5F324B8485932 ON point (polygone_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE batiment_rnb ADD CONSTRAINT FK_11917487C028CEA2 FOREIGN KEY (point_id) REFERENCES point (id)');
        $this->addSql('ALTER TABLE batiment_rnb ADD CONSTRAINT FK_119174874DE7DC5C FOREIGN KEY (adresse_id) REFERENCES adresse (id)');
        $this->addSql('ALTER TABLE point ADD CONSTRAINT FK_B7A5F324B8485932 FOREIGN KEY (polygone_id) REFERENCES batiment_rnb (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE batiment_rnb DROP CONSTRAINT FK_11917487C028CEA2');
        $this->addSql('ALTER TABLE batiment_rnb DROP CONSTRAINT FK_119174874DE7DC5C');
        $this->addSql('ALTER TABLE point DROP CONSTRAINT FK_B7A5F324B8485932');
        $this->addSql('DROP TABLE adresse');
        $this->addSql('DROP TABLE batiment_rnb');
        $this->addSql('DROP TABLE point');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
